version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 1234
      DB_NAME: car_marketplace
    depends_on:
      - db

  websocket:
    build:
      context: .
      dockerfile: utils/Dockerfile.websocket
    ports:
      - "8081:8081"

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: car_marketplace
    ports:
      - "5433:5432"
    volumes:
      -       - ./init-cars.sql:/docker-entrypoint-initdb.d/init-cars.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: